In [16]:
import pandas as pd

In [17]:
data = pd.read_csv('../01_source_data/supermarket_sales.csv', index_col=0)

In [18]:
data['Date'] = pd.to_datetime(data['Date'])

In [19]:
data.columns

Index(['Branch', 'City', 'Customer type', 'Gender', 'Product Line',
       'Unit Price', 'Quantity Sold', 'Sales Before Tax', 'Tax 5%',
       'Total Sales', 'Date', 'Time', 'Payment Method', 'Rating'],
      dtype='object')

In [20]:
data['Year'] = data['Date'].dt.year

In [21]:
data['Month Name'] = data['Date'].dt.month_name()

In [22]:
data['Day Name'] = data['Date'].dt.day_name()

In [23]:
data.to_csv('../03_analysis/supermarket_sales.csv', encoding='utf-8', index_label='Invoice ID')

In [25]:
data

,Branch,City,Customer type,Gender,Product Line,Unit Price,Quantity Sold,Sales Before Tax,Tax 5%,Total Sales,Date,Time,Payment Method,Rating,Year,Month Name,Day Name
Invoice ID,,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,522.83,26.14,548.97,2019-01-05,1:08:00 PM,Ewallet,9.1,2019,January,Saturday
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,76.40,3.82,80.22,2019-03-08,10:29:00 AM,Cash,9.6,2019,March,Friday
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,324.31,16.22,340.53,2019-03-03,1:23:00 PM,Credit card,7.4,2019,March,Sunday
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,465.76,23.29,489.05,2019-01-27,8:33:00 PM,Ewallet,8.4,2019,January,Sunday
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,604.17,30.21,634.38,2019-02-08,10:37:00 AM,Ewallet,5.3,2019,February,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,40.35,2.02,42.37,2019-01-29,1:46:00 PM,Ewallet,6.2,2019,January,Tuesday
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,973.80,48.69,1022.49,2019-03-02,5:16:00 PM,Ewallet,4.4,2019,March,Saturday
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,31.84,1.59,33.43,2019-02-09,1:22:00 PM,Cash,7.7,2019,February,Saturday
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,65.82,3.29,69.11,2019-02-22,3:33:00 PM,Cash,4.1,2019,February,Friday
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,618.38,30.92,649.30,2019-02-18,1:28:00 PM,Cash,6.6,2019,February,Monday